### ISSUE TITLE
AttributeError: module 'falcon' has no attribute 'App'

### ISSUE THREAD

**Issue by koslambrou** [RDFLib/pyLODE#105]
After executing the following command:

```
$ python pylode/server.py
```

I'm getting the following error message:

```
AttributeError: module 'falcon' has no attribute 'App'
```

**Comment by nicholascar** [comment]
I've just pushed an update to this GitHub and [pyLODE on PyPI](https://pypi.org/project/pyLODE/) that fixes this by using `api = falcon.API()` instead of `api = falcon.App()`. Not sure why that original form was used...

I've also updated the documentation for the Falcon server use and some of the HTML produced by the it to help with use.
