### ISSUE TITLE
Command not found: cannot directly run pylode on Linux bash as documented

### ISSUE THREAD

**Issue by faubulous** [RDFLib/pyLODE#168]
I've been trying to run pylode after installing it through pip3 on Python 3.10.4 using the command:

`$ pip3 install pylode`

I always got a 'bash: pylode: command not found...' error when entering the documented command on Fedora Linux:

`$ pylode test.ttl -o test.html`

After some research I found out that I need to run pylode as a module to be able to use it on the command line. So instead, the command should be:

`$ python -m pylode test.ttl -o test.html`

It would be great if you updated your documentation to mention this method. The current documentation is missing the `-m` flag.

**Comment by nicholascar** [comment]
Hi @faubulous, oh dear, it _used_ to work like that - `$ pylode ...` - so something must have broken it, probably when we went to pyLODE3. 

I am planning an update sprint in July to enable SKOS support, support for more schema.org properties and a few other things, so I see this Issue here now and I'll hopefully be able to look into this too.

Of course, if you can work out how to fix things, please do submit a PR and I've love to merge it!
