### ISSUE TITLE
Run pyLODE-as-a-service

### ISSUE THREAD

**Issue by lewismc** [RDFLib/pyLODE#23]
Hi @nicholascar hope all is going well.
We would like to host pyLODE and make it available *aaS to anyone who wants to use it. Specifically, we want to replace the LODE links in the ESIP COR (see screenshot below) with the new pyLODE which would be hosted on the same server.
What is the current status of running pyLODE as a Python service?
<img width="1440" alt="Screen Shot 2019-07-22 at 4 57 39 PM" src="https://user-images.githubusercontent.com/1165719/61672806-eef11580-aca1-11e9-81fe-e5a787f75c93.png">

**Comment by nicholascar** [comment]
Good timing @lewismc! I have just (last night) been working on better packaging for the tool to ensure anyone can host it and also creating a hosted instance. I suppose you've seen the recent commits... You'll see that pyLODE's [now on PyPI](https://pypi.org/project/pyLODE/) and dependencies are managed better than when it was only here on GitHub.

I've just about finished (a day or two to go) making a fast Python Sanic hosted instance of the tool. This instance will provide both an HTTP API to run it and also a human-input web form for direct input, file upload or URI entry. I've not made that service code public just yet for vague security reasons but can do so if you're interested.

I'm very happy for you to host your own online instance. Did you want to develop it in isolation (perhaps you have a way of going APIs you want to continue with) or did you want to co-develop with the API I'm creating? 

I would have had this API up already if I developed as I normally do but I wanted to develop more robustly this time than previously, so I'm using Sanic instead of Flask (it's faster and  more modern) and want to ensure the UI is nice (vue.js + Bootstrap) rather than plain HTML. 

Let me know your preferences: if you're already underway with dev or have an API style in mind, I might learn a bit from how you hope to host it!

**Comment by lewismc** [comment]
> ...or did you want to co-develop with the API I'm creating?

I would rather work with you. 

I pushed a very lightweight server to the following branch

**Comment by nicholascar** [comment]
Thanks Lewis, all merged in. I'll run it a couple of times and if all good, close this Issue. Happy to have and help maintain the Falcon server. Give me a sec to review if I can just replace the Sanic one I was using with this (probably can). 'll still make that vue.js front-end though and host that since it will be useful for people. Cheers, Nick

**Comment by nicholascar** [comment]
Th re is now a JSON API to invoke pyLODE as a web service at https://kirrawong.net/pylode-online
