### ISSUE TITLE
skos:historyNote Markdown support

### ISSUE THREAD

**Issue by hammar** [RDFLib/pyLODE#65]
Per the readme, skos:historyNote annotations on the ontology should have Markdown support -- but that's not working for me. E.g., in RDF/XML:

    <skos:historyNote xml:lang="en">## Version 3.1.1 is a minor release of REC that contains:
    
    * The official REC REST API (see the api/REST subdirectory)
    * O2O annotations used by the OWL2OAS generator when building that API.
    * Spelling fixes.
    </skos:historyNote>

generates the following HTML:

    <strong>History Note:</strong>
    ## Version 3.1.1 is a minor release of REC that contains:
    
    * The official REC REST API (see the api/REST subdirectory)
    * O2O annotations used by the OWL2OAS generator when building that API.
    * Spelling fixes.

which on screen of course only comes as a single long text line. Am I misunderstanding this feature -- does Markdown support as mentioned in the readme only imply that Markdown is maintained when md output is selected? Or am I doing something wrong?

Cheers,

Karl

**Comment by nicholascar** [comment]
No: you have it right. Markdown rendering's only enabled on some property values where it's expected e.g. Description/Definition but I've not so far enabled it for `historyNote`.  No real reason for that so I've enabled it just now with Commit https://github.com/RDFLib/pyLODE/commit/95043cd2418d14614f25e75df1a07951a401c982. So that functionality's there now in `master` but obviously not yet there in a full release on GitHub or PyPI.

I will have another PyPI release shortly as I try to hunt down further import problems for people using the command line versions of the program!

**Comment by dr-shorthair** [comment]
Markdown should be enabled on
- rdfs:comment
- skos:note and sub-properties
- skos:definition
- dc:description / dcterms:description

**Comment by dr-shorthair** [comment]
I also found that the description on an Ontology was handled differently to the description on all the other resources - though that was the `.exe` that is currently in the repo, which is a month old now.

**Comment by nicholascar** [comment]
`skos:historyNote` has Markdown support, as of PR #94 now merged.
