### ISSUE TITLE
Display all user-generated Annotations

### ISSUE THREAD

**Issue by rrovetto** [RDFLib/pyLODE#74]
Please add the functionality allowing pyLODE to automatically recognize and display all user-generated annotations. 

[This page ](https://github.com/RDFLib/pyLODE/#what-pylode-understands) lists what's currently recognized from rdfs, skos, etc.  And I understand that users can create profiles to allow pyLODE to recognize others, but I believe it would be very helpful to all users if pyLODE could automatically recognize any user-generated annotation. Thank you.

**Comment by nicholascar** [comment]
@rrovetto I don't think I can do that! 

Some of the precursor tools to pyLODE took the approach to allow any annotations but this leads to three issues:

1. difficulty in processing ontologies 
    - catering for any graph pattern requires difficult code
2. bad presentation 
    - catering for any graph shape requires potentially endless UI elements and least to overly complex web pages
3. loose ontology documentation styles
    - if pyLODE caters for everything, people will do anything

One of the main goals of pyLODE is to encourage certain practices of ontology documentation. It does this by recognising certain things, as per the page you point to, which have proved their worth over time. You *can* get around this with profiling, as you say, and that is by design. If someone is prepared to go to all the effort of creating a profile in pyLODE, there's probably a good reason for it e.g. lots of ontologies out there that use those annotations or perhaps a well though through theory as to why those properties should be catered for. 

Profiles are defined sets of things, not open-ended things, so the OWLP (Profile of OWL) that pyLODE understands for instance is a closed set of properties. Please do point out specific Dublin Core, schema.org, SKOS or similar properties where you see I've missed them and think that they might conceptually fit into the existing OWLP or SKOSP profiles and I'll consider those. 

Otherwise, do create your own profile for anything! I'll be adding better documentation for this... eventually.
