### ISSUE TITLE
Embed Google Analytics in pyLODE

### ISSUE THREAD

**Issue by lewismc** [RDFLib/pyLODE#80]
We would like to activate Google Analytics on pyLODE in an attempt to obtain more holistic usage insights. I have no idea where this would be added in pyLODE... @nicholascar can you help me pinpoint this?
Thanks

**Comment by nicholascar** [comment]
In the file *server.py*, there is already a post-HTML generation tidy-up, see https://github.com/RDFLib/pyLODE/blob/701bcb6cbe4cc79c50ca02a7f203ac9f4f7e5b3a/pylode/server.py#L12. It just hides the placeholder image since you can’t add in a hand-made image when auto-generating docs via Falcon.

Since your Google Analytics code will be instance-specific, I suggest you branch pyLODE making a SWEET branch locally for your deployment and then adding in the HTML + JavaScript in *server.py* after the image hiding lines.

**Comment by lewismc** [comment]
Thanks @nicholascar I'm going to see if there is a more elegant way to inject this parameter... maybe a [Dockerfile](https://docs.docker.com/engine/reference/commandline/build/#options) with a `build-arg`. I'll try there and see how far I get.

**Comment by carueda** [comment]
Agree, this should not require a fork, but just some local configuration file that can be customized in a particular installations: pyLODE would consume such config file, for example to include a snipped in the generated HTML with the google analytics stuff.  (Other uses also become possible in a more flexible manner.)

**Comment by nicholascar** [comment]
I look forward to seeing fancy solutions here! I’ll do what I can to help.

**Comment by nicholascar** [comment]
Added by PR #83
