### ISSUE TITLE
Remove argparse in requirements

### ISSUE THREAD

**Issue by koslambrou** [RDFLib/pyLODE#96]
I suggest removing `argparse` from the `requirements.txt` since it is included in the standard library.

Acceptable ?

**Comment by nicholascar** [comment]
@koslambrou thanks for the suggestion. I've removed `argparse` and am now removing other requirements too. If I shift all those requirements just needed for Falcon server implementations - `beautifulsoup4`, `falcon` & `gunicorn` - to a new file `requirements.server.txt` then `requirements.txt shrinks to just:

```
jinja2
markdown
rdflib>=5.0.0
rdflib-jsonld>=0.5.0
requests
```

I can't remove `requests` since that's required by certain `rdflib` functions but that's being worked on by the RDFlib maintainers (me and others!!). If we can remove that, and fold `rdflib-jsonld` into `rdflib` within the next month or so, then the dependencies will shrink further to just:

```
jinja2
markdown
rdflib>=6.0.0
```

where `rdflib>=6.0.0` contains `rdflib-jsonld`.

**Comment by nicholascar** [comment]
I've tidied up the requirements.txt and implemented requirements.server.txt and the Dockerfile builder's adding in the extra packages from there so requirments.txt is now just:

```
jinja2
markdown
rdflib>=5.0.0
rdflib-jsonld>=0.5.0
requests
```
